export const products = [
  {
    productName: "Lightsaber",
    productId: "LS-001",
    vendor: "Galactic Emporium",
    category: "weapons",
    productDescription:
      "A legendary weapon of the Jedi, this blue lightsaber features a plasma blade powered by a kyber crystal. Perfect for collectors and aspiring Force users.",
    productDetails: {
      dimensions: "120cm x 4cm x 4cm",
      color: "Blue",
      material: "Plasteel",
      weight: "1.2kg",
    },
    price: 1000,
    quantityInStock: 0,
    starRating: 4.2,
    numberOfReviews: 87,
    topReview:
      "StarWars Nerd says light sabers in this generation are lower quality than last generation. Pass for now.",
    tags: [
      "starwars",
      "lightsaber",
      "collectible",
      "toy",
      "light side",
      "oba wan kenobi",
      "stylish",
      "jedi",
      "blue",
      "Galactic Emporium",
      "Plasteel",
      "light",
      "saber",
    ],
    productImage: "/lightyear/images/products/lightsaber-blue.png",
    frequentlyReturned: false,
    relatedProducts: ["LS-002", "LS-003", "LS-004", "LS-005", "LS-006"],
  },
  {
    productName: "Sith Lightsaber",
    productId: "LS-002",
    vendor: "Dark Side Supplies",
    category: "weapons",
    productDescription:
      "Embrace the power of the dark side with this red Sith lightsaber. Features a durable hilt and a menacing crimson blade for ultimate intimidation.",
    productDetails: {
      dimensions: "125cm x 4cm x 4cm",
      color: "Red",
      material: "Durasteel",
      weight: "1.3kg",
    },
    price: 250,
    quantityInStock: 5,
    starRating: 5.0,
    numberOfReviews: 102,
    topReview: "Darth Reviewer: The red glow is menacing. Perfect for cosplay.",
    tags: ["starwars", "lightsaber", "sith", "collectible"],
    productImage: "/lightyear/images/products/lightsaber-red.png",
    frequentlyReturned: false,
    relatedProducts: ["LS-001", "LS-003", "LS-007", "LS-008", "LS-009"],
  },
  {
    productName: "Jedi Training Remote",
    productId: "JT-001",
    vendor: "Jedi Temple Shop",
    category: "other",
    productDescription:
      "Sharpen your Jedi reflexes with this authentic training remote. Floats and fires harmless practice bolts for safe and fun lightsaber training.",
    productDetails: {
      dimensions: "15cm x 15cm x 15cm",
      color: "Silver",
      material: "Alloy",
      weight: "0.5kg",
    },
    price: 150.0,
    quantityInStock: 20,
    starRating: 4.0,
    numberOfReviews: 45,
    topReview:
      "Padawan Paul: Great for practicing, but batteries run out fast.",
    tags: ["starwars", "training", "jedi", "toy"],
    productImage: "/lightyear/images/products/jedi-remote.png",
    frequentlyReturned: true,
    relatedProducts: ["LS-001", "LS-002", "JT-002", "JT-003", "LS-003"],
  },
  {
    productName: "Mandalorian Helmet",
    productId: "MH-001",
    vendor: "Mando Merch",
    category: "armor",
    productDescription:
      "Step into the shoes of a Mandalorian with this screen-accurate helmet. Crafted from high-quality materials for cosplay or display.",
    productDetails: {
      dimensions: "30cm x 25cm x 25cm",
      color: "Silver",
      material: "Beskar",
      weight: "2.5kg",
    },
    price: 49.99,
    quantityInStock: 3,
    starRating: 5.0,
    numberOfReviews: 210,
    topReview: "HelmetHead: This is the way. Superb craftsmanship.",
    tags: ["starwars", "mandalorian", "helmet", "cosplay"],
    productImage: "/lightyear/images/products/mandalorian-helmet.png",
    frequentlyReturned: false,
    relatedProducts: ["LS-001", "LS-002", "MH-002", "MH-003", "JT-001"],
  },
  {
    productName: "Grogu Plush",
    productId: "GP-001",
    vendor: "Toy Galaxy",
    category: "other",
    productDescription:
      "Bring home the adorable Grogu (Baby Yoda) with this soft and cuddly plush. Perfect for fans of all ages and a must-have for any Star Wars collection.",
    productDetails: {
      dimensions: "25cm x 20cm x 15cm",
      color: "Green",
      material: "Plush",
      weight: "0.3kg",
    },
    price: 25.99,
    quantityInStock: 50,
    starRating: 4.8,
    numberOfReviews: 320,
    topReview: "BabyYodaFan: So cute! My kid loves it.",
    tags: ["starwars", "grogu", "plush", "toy"],
    productImage: "/lightyear/images/products/grogu-plush.png",
    frequentlyReturned: false,
    relatedProducts: ["GP-002", "LS-001", "MH-001", "JT-001", "LS-003"],
  },
  {
    productName: "Stormtrooper Blaster",
    productId: "SB-001",
    vendor: "Imperial Surplus",
    category: "weapons",
    productDescription:
      "Replica of the iconic Stormtrooper blaster. Lightweight and safe for cosplay, conventions, or display in your Star Wars collection.",
    productDetails: {
      dimensions: "60cm x 10cm x 20cm",
      color: "White/Black",
      material: "Plastic",
      weight: "1.0kg",
    },
    price: 120,
    quantityInStock: 25,
    starRating: 3.9,
    numberOfReviews: 60,
    topReview: "TrooperTom: Misses a lot, just like the movies.",
    tags: ["starwars", "blaster", "stormtrooper", "toy"],
    productImage: "/lightyear/images/products/stormtrooper-blaster.png",
    frequentlyReturned: true,
    relatedProducts: ["SB-002", "LS-001", "MH-001", "JT-001", "GP-001"],
  },
  {
    productName: "Millennium Falcon Model",
    productId: "MF-001",
    vendor: "Corellian Collectibles",
    category: "other",
    productDescription:
      "Detailed model of the Millennium Falcon, the fastest ship in the galaxy. Perfect for display or as a centerpiece in your Star Wars collection.",
    productDetails: {
      dimensions: "50cm x 35cm x 10cm",
      color: "Gray",
      material: "Plastic",
      weight: "3.0kg",
    },
    price: 148,
    quantityInStock: 7,
    starRating: 4.6,
    numberOfReviews: 150,
    topReview: "HanSoloFan: Fastest model in the galaxy.",
    tags: ["starwars", "millennium falcon", "model", "collectible"],
    productImage: "/lightyear/images/products/millennium-falcon.png",
    frequentlyReturned: false,
    relatedProducts: ["MF-002", "LS-001", "MH-001", "SB-001", "GP-001"],
  },
  {
    productName: "Darth Vader Mask",
    productId: "DV-001",
    vendor: "Sith Relics",
    category: "armor",
    productDescription:
      "Channel the dark side with this Darth Vader mask. Features authentic detailing and voice modulation for the ultimate cosplay experience.",
    productDetails: {
      dimensions: "35cm x 25cm x 25cm",
      color: "Black",
      material: "Plastic",
      weight: "1.8kg",
    },
    price: 98.0,
    quantityInStock: 10,
    starRating: 4.5,
    numberOfReviews: 98,
    topReview: "VaderVoice: Breathing sound is spot on.",
    tags: ["starwars", "darth vader", "mask", "cosplay"],
    productImage: "/lightyear/images/products/darth-vader-mask.png",
    frequentlyReturned: false,
    relatedProducts: ["DV-002", "LS-002", "SB-001", "MH-001", "JT-001"],
  },
  {
    productName: "Rey’s Staff",
    productId: "RS-001",
    vendor: "Scavenger Supplies",
    category: "weapons",
    productDescription:
      "A faithful replica of Rey’s staff from Jakku. Lightweight and durable, ideal for cosplay or as a unique display piece.",
    productDetails: {
      dimensions: "180cm x 5cm x 5cm",
      color: "Brown",
      material: "Plastic",
      weight: "2.0kg",
    },
    price: 150,
    quantityInStock: 8,
    starRating: 4.1,
    numberOfReviews: 34,
    topReview: "DesertDweller: Lightweight and looks authentic.",
    tags: ["starwars", "rey", "staff", "toy"],
    productImage: "/lightyear/images/products/reys-staff.png",
    frequentlyReturned: false,
    relatedProducts: ["RS-002", "LS-001", "GP-001", "MH-001", "JT-001"],
  },
  {
    productName: "Kylo Ren Crossguard Lightsaber",
    productId: "LS-003",
    vendor: "First Order Forge",
    category: "weapons",
    productDescription:
      "Wield the power of Kylo Ren with this crossguard lightsaber replica. Features a unique hilt design and glowing red blades.",
    productDetails: {
      dimensions: "130cm x 6cm x 6cm",
      color: "Red",
      material: "Durasteel",
      weight: "1.5kg",
    },
    price: 299.99,
    quantityInStock: 2,
    starRating: 4.3,
    numberOfReviews: 77,
    topReview: "KnightOfRen: Crossguard is a cool touch, but a bit heavy.",
    tags: ["starwars", "lightsaber", "kylo ren", "collectible"],
    productImage: "/lightyear/images/products/kylo-ren-lightsaber.png",
    frequentlyReturned: false,
    relatedProducts: ["LS-002", "LS-001", "MH-001", "DV-001", "SB-001"],
  },
];
